server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  sleuth:
    sampler:
      probability: 1.0   # em prod deve ser 0.05
  application:
    name: api-gateway
  cloud:
      gateway:
        discovery:
          locator:
            enabled: true
  #          lower-case-service-id: true
        routes:
          - id: cambio-service
            uri: lb://cambio-service
            predicates:
              - Path=/cambio-service/**
          - id: book-service
            uri: lb://book-service
            predicates:
              - Path=/book-service/**
